name: Pull request workflow

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test using iPhone 14 Simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        env:
          scheme: Spoof
          platform: ${{ 'iOS Simulator' }}
        run: |
          destination="platform=iOS Simulator,name=iPhone 14"
          xcodebuild build-for-testing -scheme "$scheme" -project "Spoof.xcodeproj" -destination "$destination"
      - name: Test
        env:
          scheme: Spoof
          platform: ${{ 'iOS Simulator' }}
        run: |
          destination="platform=iOS Simulator,name=iPhone 14"
          xcodebuild test-without-building -scheme "$scheme" -project "Spoof.xcodeproj" -destination "$destination" -only-testing:Spoof/SpoofUITests/SpoofUITestsLaunchTests/testLaunch
